Repository AY2324S1-CS2113-W12-2/tp, pull requests merged in 2023-11, with the labels that each got.

#73 Branch file storage
  .gitignore
  data/mc/the.txt
  data/testUser.txt
  data/yuxuan.txt
  src/main/java/cashleh/CashLeh.java
  src/main/java/cashleh/FileStorage.java
  src/main/java/cashleh/budget/Budget.java
  src/main/java/cashleh/budget/BudgetHandler.java
  src/main/java/cashleh/budget/Progress.java
  src/main/java/cashleh/commands/DeleteBudget.java
  src/main/java/cashleh/commands/ViewBudget.java
  src/test/java/cashleh/FileStorageTest.java
  src/test/java/cashleh/budget/BudgetHandlerTest.java
  src/test/java/cashleh/transaction/FinancialStatementTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#107 PE-D Bug Fixing 1
  data/testUser.txt
  docs/Images/budgetHandler_classDiagram.png
  docs/Images/budgetHandler_sequenceDiagram.png
  docs/UserGuide.md
  docs/uml/budgetHandler_classDiagram.puml
  docs/uml/budgetHandler_sequenceDiagram.puml
  src/main/java/cashleh/CashLeh.java
  src/main/java/cashleh/commands/DeleteBudget.java
  src/main/java/cashleh/parser/Parser.java
  src/main/java/cashleh/transaction/FinancialStatement.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, severity.High

#108 Fixed various bugs in reported issues
  data/.txt
  data/mc.txt
  data/testUser.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/stringTokenizer.png
  docs/uml/stringTokenizer.puml
  src/main/java/cashleh/CashLeh.java
  src/main/java/cashleh/exceptions/CashLehDateParsingException.java
  src/main/java/cashleh/parser/Parser.java
  src/test/java/cashleh/parser/ParserTest.java
  src/test/java/cashleh/parser/StringTokenizerTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High

#110 Fix Issues from PED
  docs/UserGuide.md
  src/main/java/cashleh/parser/FilterSequenceDiagram.puml
  src/main/java/cashleh/parser/Parser.java
  src/main/java/cashleh/transaction/ExpenseStatement.java
  src/main/java/cashleh/transaction/FinancialStatement.java
  src/main/java/cashleh/transaction/IncomeStatement.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/Benedict.txt
Labels: priority.Medium, severity.Medium
