Repository AY2324S1-CS2113-W12-2/tp, pull requests merged in 2023-10, with the labels that each got.

#23 Initialisation and exit
  src/main/java/cashleh/CashLeh.java
  src/main/java/cashleh/Input.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#25 Level-1-income
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/cashleh/Income.java
  src/main/java/cashleh/IncomeStatement.java
  src/main/java/cashleh/commands/AddIncome.java
  src/main/java/cashleh/commands/Command.java
  src/main/java/cashleh/commands/DeleteIncome.java
  src/main/java/cashleh/commands/ViewIncomes.java
  src/test/java/cashleh/CashLehTest.java
  src/test/java/cashleh/IncomeStatementTest.java
  src/test/java/cashleh/IncomeTest.java
Labels: type.Task, priority.High

#55 Add assertions to string tokenizer
  data/mc/the.txt
  data/testUser.txt
  src/main/java/cashleh/Ui.java
  src/main/java/cashleh/parser/Parser.java
  src/main/java/cashleh/parser/StringTokenizer.java
  src/main/java/cashleh/transaction/Expense.java
  src/main/java/cashleh/transaction/Income.java
  src/main/java/cashleh/transaction/Transaction.java
  src/test/java/cashleh/parser/StringTokenizerTest.java
  src/test/java/cashleh/transaction/ExpenseStatementTest.java
  src/test/java/cashleh/transaction/ExpenseTest.java
  src/test/java/cashleh/transaction/IncomeStatementTest.java
  src/test/java/cashleh/transaction/IncomeTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#64 V2.0
  data/yuxuan.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/architeture.png
  docs/images/main_example.png
  docs/uml/Architeture.puml
  docs/uml/main_example.puml
  src/main/java/cashleh/parser/Parser.java
  src/test/java/cashleh/parser/ParserTest.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium
